### ISSUE TITLE
Docs are kill

### ISSUE THREAD

**Issue by remexre** [cogciprocate/ocl#47]
http://doc.cogciprocate.com/ocl/ocl/ -> https://www.dynu.com/Support/Offline?domainName=cogciprocate.com&Hostname=doc.cogciprocate.com

GitHub Pages? With #21?

**Comment by c0gent** [comment]
Strange, it's working for me. Try again?

**Comment by remexre** [comment]
Still happening for me... do you have it in your hosts file, by any chance? (Or it expired recently and your DNS still has it in cache?)

**Comment by c0gent** [comment]
It's not in my hosts file but it's probably cached on my router. Let me see...

In the meanwhile are you able to hit cogciprocate.com at all?

This is the first trouble I've seen with Dynu DNS but this is the first year I've had them so I dunno.

**Comment by c0gent** [comment]
It's down on my mobile connection so it's not just you.

I'll get to the bottom of it.

And yes I probably should move the docs to github.

**Comment by remexre** [comment]
Firefox with clean profile (so no local cache), offline for me. Ditto for Chrome on phone's LTE, never tried to access before from there. Main browser is Vivaldi, so it's not a cache sync issue to the phone.

**Comment by remexre** [comment]
A basic `travis.yml` to just build the docs would be:

```yaml
language: rust
rust:
- stable

script:
- cargo build --verbose
- cargo doc --verbose
after_success:
- echo '<meta http-equiv="refresh" content="0;url=ocl/index.html">' > target/doc/index.html
- pip install --user ghp-import
- ghp-import -n target/doc
- git push -qf https://${GH_TOKEN}@github.com/cogciprocate/ocl.git gh-pages
```

after you put a token with a [Personal Access Token](https://github.com/settings/tokens) into the `GH_TOKEN` environment variable for the build. The token needs the `public_repo` permission and no others. (this is decently poorly documented; took me >6hrs of trial commits to get it set up...)

This is assuming you don't want to run the tests on Travis per #21. If you do, delete the `script:` and `- cargo build --verbose` lines, then move the `- cargo doc --verbose` line directly under the `after_success:` line.
